build_image:
  image: docker:git
  services:
  - docker:dind
  
  before_script:  
  - apk update && apk add curl && apk add python
  
  
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

